package fan.fancy.iam.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import fan.fancy.iam.mapper.UserMapper;
import fan.fancy.iam.pojo.entity.UserDO;
import fan.fancy.iam.pojo.query.UserQuery;
import fan.fancy.iam.service.UserService;
import fan.fancy.toolkit.lang.StringUtils;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * 用户接口实现类.
 *
 * <p>注意：当前设计下 IAM 端不再持有 user_identity 表，认证信息由 authorization-server 管理。
 * 本类只处理 IAM 业务用户（昵称、头像、性别、生日等）。
 *
 * @author Fan
 */
@Service
@RequiredArgsConstructor
public class UserServiceImpl implements UserService {

    private final UserMapper userMapper;

    @Override
    public Page<UserDO> page(UserQuery query) {
        LambdaQueryWrapper<UserDO> queryWrapper = new LambdaQueryWrapper<>();
        queryWrapper.like(StringUtils.isNotBlank(query.getUsername()), UserDO::getNickname, query.getUsername());
        return userMapper.selectPage(new Page<>(query.getCurrentPage(), query.getPageSize()), queryWrapper);
    }

    @Override
    public UserDO getById(String id) {
        return userMapper.selectById(id);
    }

    @Override
    public int create(UserDO userDO) {
        return userMapper.insert(userDO);
    }

    @Override
    public int update(UserDO userDO) {
        return userMapper.updateById(userDO);
    }

    @Override
    public int deleteById(String id) {
        return userMapper.deleteById(id);
    }

    @Override
    public int deleteByIds(List<String> ids) {
        return userMapper.deleteByIds(ids);
    }

    /**
     * OAuth2 callback 后由 authorization-server 调用.
     *
     * <p>userId 必须由 auth 服务生成（雪花）后传入，IAM 不再兜底生成。
     * IAM 只写业务行（不写 user_identity）。
     */
    @Override
    @Transactional
    public Integer createUser(UserDO userDO) {
        if (userDO.getId() == null) {
            throw new IllegalArgumentException("userId is required, must be generated by authorization-server");
        }
        return userMapper.insert(userDO);
    }
}